# Generated by Django 4.0.3 on 2022-04-05 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_type', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supers',
            name='catchphrase',
        ),
        migrations.AddField(
            model_name='supers',
            name='super_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='super_type.supertype'),
        ),
    ]
