# Generated by Django 4.0.3 on 2022-04-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_remove_supers_catchphrase_supers_super_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supers',
            name='alter_ego',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supers',
            name='catchphrase',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supers',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supers',
            name='primary_ability',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supers',
            name='secondary_ability',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
